name: build-test-linux-on-tag
on:  
  push:
    tags:
      - '*'
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  linux:
    runs-on: ubuntu-latest
    container:
      image: swift:latest
    steps:
    - name: Clean Workspace
      uses: AutoModality/action-clean@v1.1.0
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: swift build -vv
    - name: Test
      run: swift test -vv
      