name: build-test-mac-on-tag
on:  
  push:
    tags:
      - '*'
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  mac:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -vv
    - name: Test
      run: swift test -vv